services:
  - type: web
    name: metas-backend
    env: node
    plan: free
    region: oregon

    buildCommand: npm ci && npm run build
    startCommand: npm run start

    envVars:
      - key: NODE_ENV
        value: production

      - key: HOST
        value: 0.0.0.0

      - key: PORT
        value: 10000

      - key: LOG_LEVEL
        value: info

      - key: APP_KEY
        sync: false

      # Database (Neon)
      - key: DATABASE_URL
        sync: false
      - key: DB_CONNECTION
        value: pg

      - key: DB_HOST
        value: ep-billowing-scene-ahmxxxj5-pooler.c-3.us-east-1.aws.neon.tech

      - key: DB_PORT
        value: "5432"

      - key: DB_USER
        value: neondb_owner

      - key: DB_PASSWORD
        sync: false

      - key: DB_DATABASE
        value: neondb